<?php

/**
 * @file
 * Contains help_widgets.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function help_widgets_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the help_widgets module.
    case 'help.page.help_widgets':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for displaying contextual help texts and examples') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function help_widgets_theme() {
  return [
    'help_widgets' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function help_widgets_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
    $formObject = $form_state->getFormObject();

    if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
        $entity = $formObject->getEntity();
        if ($entity->getEntityTypeId() === 'node') {
            $form['#attached']['library'][] = 'help_widgets/basis';
        }
    }

}
