#!/bin/bash

drush mim file_hazards_icons --sync
drush mim tax_hazards_relevant --sync
drush mim tax_hazards --sync
drush mim tax_hazards --update
drush mim tax_calculation_methods --sync
drush mim tax_countries --sync
drush mim tax_cities_regions --sync
drush mim tax_co_benefits --sync
drush mim tax_co_benefits --update
drush mim tax_currency --sync
drush mim tax_dp_roles --sync
drush mim tax_dp_keywords --sync
drush mim tax_resource_types --sync
drush mim tax_license_types --sync
drush mim tax_dp_servicetypes --sync
drush mim tax_dp_var_meaning --sync
drush mim tax_dp_variables --sync
drush mim tax_el_at_risk_relevant --sync
drush mim tax_el_at_risk --sync
drush mim tax_el_at_risk --update
drush mim tax_emission_scenarios --sync
drush mim tax_eu_gl --sync
drush mim tax_eu_gl --update
drush mim tax_impact_scenarios --sync
drush mim tax_impact_scenarios --update
drush mim node_dp_license --sync
drush mim node_dp_source --sync
drush mim tax_land_use --sync
drush mim tax_le_params --sync
drush mim tax_local_haz_change --sync
drush mim tax_rep_image_cat --sync
drush mim tax_sectors --sync
drush mim tax_sectors --update
drush mim tax_sol_offer_types --sync
drush mim tax_default_tags --sync
drush mim node_extended_iframe --sync
drush mim node_view_as_app --sync
drush mim node_gl_step --sync
drush mim tax_study_types --sync
drush mim node_contextual_help --sync
drush mim node_adapt_opt_eff --sync
drush mim node_adapt_opt --sync
drush mim node_dp_contributor --sync
drush mim node_dp_price --sync
drush mim node_dp_reference --sync
drush mim node_spatial_extent --sync
drush mim node_temporal_extent --sync
drush mim node_gridband_info --sync
drush mim node_gridinfo --sync
drush mim node_dp_parameter --sync
drush mim node_spatial_byscale --sync
drush mim node_spatial_bydistance --sync
drush mim node_threshold --sync
drush mim node_dp_resource --sync
drush mim node_dp_vulnerability --sync
drush mim paragraph_va_relations --sync
drush mim node_dp --sync
